pipeline {
    agent {
        docker{
            image 'ruby'
        }
    }

    stages {
        stage('Hooks') {
            steps {
                sh 'cd api && bundle install'
            }
        }
        stage('Executando rspec') {
            steps {
                sh 'cd api && rspec'
            }
        }
    }
}
