# frozen_string_literal: true

gem "allure-cucumber"
source "https://rubygems.org"
gem "cucumber", "5.2"
gem "capybara", "3.33"
gem "selenium-webdriver", "3.142.7"
gem "rspec", "3.10"
gem "faker", "2.14"
gem "mongo", "2.13.1"
gem "pry"
gem 'httparty', '0.18.1'
gem 'webdrivers'
